### ISSUE TITLE
Google Maps Error

### ISSUE THREAD

**Issue by babycorp** [harsh159357/contacts#2]
Compiler message:
lib/pages/google_place_search.dart:25:48: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
GoogleMapsPlaces _places = new GoogleMapsPlaces(GOOGLE_PLACE_API_KEY);

How to fix this ?

**Comment by harsh159357** [comment]
@babycorp following bug has been fixed please pull the latest changes from the master branch.

**Comment by harsh159357** [comment]
@babycorp Issue has been resolved as flutter_google_places_autocomplete library was deprecated so flutter_google_places is used now.
