### ISSUE TITLE
phpbackend not work proper

### ISSUE THREAD

**Issue by craftbox2245** [harsh159357/contacts#4]
i put it in ma backend but it not work proper 
like this :
<br />
<b>Fatal error</b>: Call to undefined method Log::create() in <b>D:\xampp\htdocs\phpbackend\objects\Contact.php</b> on line <b>258</b><br />

please help me @harsh159357

**Comment by harsh159357** [comment]
@craftbox2245 If it is still not working let me know or we can connect remotely using anydesk

**Comment by harsh159357** [comment]
@craftbox2245 If you are still facing any problem reopen the issue.
