### ISSUE TITLE
Question: Imperative prog

### ISSUE THREAD

**Issue by adrianvintu** [harsh159357/contacts#5]
I noticed the ProgressDialog has methods to call from outside, which delegate to internal state.

```
  void hide() {
    progressDialogState.hide();
  }
```

This looks like imperative programming. Is this ok by the Flutter rules? Isn't Flutter declarative programming?

- Newbee here

**Comment by harsh159357** [comment]
@adrianvintu Yes it is okay to use (There is no specific rule in flutter for state management).
Even if you have seen source for progressDialogState.hide() it is just changing the opacity property using setState()
`  
void hide() {
    setState(() {
      opacity = false;
    });
  }
`
Also note that this is the basic state management approach we do in flutter. Also you are good to follow any strategy you want. 

I am sharing some links with you do check them out -
https://flutter.dev/docs/development/data-and-backend/state-mgmt/options

https://flutterx.com/ (if you want explore flutter further )

**Comment by adrianvintu** [comment]
Thank you @harsh159357
